./parse/bools.c \
./parse/fill_data.c \
./parse/get_next_line.c \
./parse/get_next_line_utils.c \
./parse/list_op.c \
./parse/mini_libft/ft_atoi.c \
./parse/mini_libft/ft_split.c \
./parse/mini_libft/ft_strchr.c \
./parse/mini_libft/ft_strdup.c \
./parse/mini_libft/ft_strjoin.c \
./parse/mini_libft/ft_strlen.c \
./parse/mini_libft/ft_strncmp.c \
./parse/mini_libft/ft_strrchr.c \
./parse/mini_libft/ft_strtrim.c \
./parse/mini_libft/ft_substr.c \
./parse/mini_libft/putendl_fd.c \
./parse/parse.c \
./parse/parse_header.c \
./parse/parse_map.c \
./srcs/collisions.c \
./srcs/dda.c \
./srcs/doors.c \
./srcs/draw_line.c \
./srcs/images.c \
./srcs/init.c \
./srcs/key_hooks.c \
./srcs/main.c \
./srcs/mini_map.c \
./srcs/mouse_hooks.c \
./srcs/ray_casting.c \
./srcs/render_column.c \
./srcs/sprites/init_sprite.c \
./srcs/sprites/set_sprite.c \
./srcs/sprites/sprites.c \
./srcs/update_door.c \
./srcs/update_frame.c \
./srcs/utilities.c \
./srcs/window_handling.c \
./utils/lst_door.c \
./utils/lst_heap.c \
./utils/lst_img.c \
./utils/lst_sprite.c \
./utils/talloc.c \
./utils/terror.c
